name: 中青浏览赚
on:
  workflow_dispatch:
  schedule:
     - cron: '*/30 0-3 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        YOUTH_START: ${{ secrets.YOUTH_START }}
        YOUTH_END: ${{ secrets.YOUTH_END }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        if: env.YOUTH_START
        run: |
          npm install
      - name: '运行 【中青浏览赚】'
        if: env.YOUTH_START
        run: |
          node youth_gain.js
        env:
          YOUTH_NOTIFY_CONTROL: ${{ secrets.YOUTH_NOTIFY_CONTROL }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}flow to help you get started with Actions
