name: 中青自动阅读

on:
  workflow_dispatch:
  schedule:
     - cron: '3 1-20/2 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ: ${{ secrets.YOUTH_READ }}
      YOUTH_READ2: ${{ secrets.YOUTH_READ2 }}
      YOUTH_READ3: ${{ secrets.YOUTH_READ3 }}
      YOUTH_READ4: ${{ secrets.YOUTH_READ4 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青自动阅读一45H】'
        if: env.YOUTH_READ
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ }}
          YOUTH_TIME: ${{ secrets.YOUTH_TIME }}

      - name: '运行 【中青自动阅读二50W】'
        if: env.YOUTH_READ2
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ2 }}
          
      - name: '运行 【中青自动阅读三43S】'
        if: env.YOUTH_READ3
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ3 }}
          
      - name: '运行 【中青自动阅读四47s】'
        if: env.YOUTH_READ4
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ4 }}


